### ISSUE TITLE
PWA not loading service-worker.js

### ISSUE THREAD

**Issue by ggm-dev** [magesuite/magesuite#67]
Hello - 
Testing on magento 2.4.0 and magesuite ^6.0.0 - I installed PWA and PWA-notifications modules. 

Modules have installed correctly, are enabled and I even see Notifications tab available in customer account of frontend, however I don't see service-worker.js or manifest.json loading on frontend. Are there any other config settings that I need to be aware of or extra steps?

I see that PWA is working correctly on the demo.magesuite.io, but that's still on magento v2.3.

Anyone else having issues?

**Comment by diwipl** [comment]
Hi,

Can you show screeenshot of PWA settings scoped to store view where service-worker.js and manifest.json are absent ?

**Comment by ggm-dev** [comment]
Hi -  I meant to post an update to ticket to say issue was resolved by switching to https.  But while it's fresh on my mind - do you have any additional documentation on how pwa-notifications are intended to work?  I tried to test on demo site but it appears that it's not enabled on the customer side. 

Thanks!

**Comment by diwipl** [comment]
So PWA notifications is a basic framework for sending notifications to chrome/firefox browsers on desktop and android. iOS is not supported.

Subscription to notification can only be done on checkout success page.

Currently we have only one event that is sending notifications, it happens when order was shipped and customer had notifications activated.

In order to send notifications there is a consumer defined that has to be turned on 
`bin/magento queue:consumers:start PwaNotificationSend --max-messages=1000`

**Comment by diwipl** [comment]
And to clarify, this is still unfinished and work in progress. We happily accept any contributions to extend documentation/further events.

**Comment by ggm-dev** [comment]
Thanks Krzysztof - Very helpful.   What's the best way to get in touch for
custom work and extending functionality?

David

**Comment by diwipl** [comment]
Here on github, we do not have any other way for submitting ideas so issues can be used for that. Also this increases transparency and other people can engage and give their ideas.

**Comment by mborkowski** [comment]
Btw, we are currently also working on Back In Stock feature. I'm writing it here because this will include not only e-mail subscription but also push notifications. 
This feature will contain some minor changes in magesuite-pwa-notification's JS files so that it can be reusable and more elastic.
