### ISSUE TITLE
How can I create a new ContentElement?

### ISSUE THREAD

**Issue by Scarbous** [magesuite/magesuite#68]
Hallo,
Ist es möglich, nicht nur ein Inhaltselement außer Kraft zu setzen?

Ich möchte ein neues Slide-Element und ein Spalten-Elemente erstellen.
Vielleicht auch Kundenspezifische Elemente erstellen.

**Comment by mborkowski** [comment]
Hi @Scarbous 
Could you please provide more details? I don't understand your question, it would be nice if you could edit issue and provide as much details as possible

**Comment by mborkowski** [comment]
Thanks for edit, but I'm still struggling to understand your problem. MageSuite is a huge set of features, could you please specify what slides, columns and customer-specific elements do you mean?

**Comment by Scarbous** [comment]
With MageSuite  I can edit CMS-Pages a very nice way. Now I want to use custom elements to edit the CMS-Pages.
So add a new element to the "Content Constructor".

**Comment by mborkowski** [comment]
Ok, now I get it. 
So since there's single point of entry for all components this is currently not possible. I mean you can of course add it but it will be overriden anyways after any update. It is however nice feature request, we will consider possibility to inject custom component from another module when we're going to plan refactor of Content Constructor.
