### ISSUE TITLE
HOW-TO add an input field to set additional CSS classnames to CC components?

### ISSUE THREAD

**Issue by frqnck** [magesuite/magesuite#93]
As per title, how to add an input field to a CC component to add an arbitrary CSS classnames?
What files need to be edited? An example would be very handy?

Reference: https://github.com/magesuite/content-constructor-admin/issues/8

**Comment by frqnck** [comment]
Would it be possible to have a transcript of the info from the following WIKI page -or- gain access to that wiki? 

Any feedback on this would be appreciated. Thanks.

https://creativestyle.atlassian.net/wiki/spaces/CSHOP/pages/41977882/Custom+fields+Teaser+based+components

**Comment by mborkowski** [comment]
Hi @frqnck 
So, it is possible but currently only for Image Teaser component (as a CC-component) and for the Teaser subcomponent that is used in some other components. Those, can use so called "custom fields" that by XML configuration can either add defined CSS class to the Image Teaser (or single teaser in another component) or can add custom content that can be provided by editor. 

I can't provide access to our internal docs to anyone, but I can share this article, as it describes entire concept of "custom fields". So there you go:

---

Starting from 28th June 2019 you are able to add custom fields to the Image Teaser component per project and all Content Constructor components that are based on teasers. The scope is however limited for teaser based CC components as it only gives you the ability to add custom features per teaser, not for entire component. This can be done only for Image Teaser (at least for the moment of writing this article).

This feature brings a lot of new possibilities. For Magesuite projects it's very nice to have only base features and those you really use instead of maintaining all custom things that were introduced for other clients.

Below you can see table with all custom types of fields/component you can use in your project. Don't worry if it's not obvious yet how to implement this, we will get to this topic later in this article.

<table>
  <thead>
    <tr>
      <th>Field type</th>
      <th>Description</th>
      <th>Vars available</th>
      <th>Code sample</th>
      <th>Effect</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>textarea</td>
      <td>Textarea for more complex content. Remember to not provide too much of it as frontend might have problems to fit all of it.</td>
      <td>Same as for "input"</td>
      <td>
        <strong>theme-myproject/src/etc/view.xml</strong><br>
<pre>...
  &lt;var name="fields"&gt;
    &lt;var name="1"&gt;
      &lt;var name="label"&gt;Badge text&lt;/var&gt;
      &lt;var name="type"&gt;textarea&lt;/var&gt;
      &lt;var name="model"&gt;badge_text&lt;/var&gt;
      &lt;var name="hint"&gt;&lt;![CDATA[
        Add content with special markup, e.g.:
        - &lt;small&gt;Only&lt;/small&gt; {{price sku="some_sku"}}
        - {{sku sku="some_sku"}}
        - &lt;big&gt;Only&lt;/big&gt; {{qty sku="some_sku"}} left
      ]]&gt;&lt;/var&gt;
    &lt;/var&gt;
  &lt;/var&gt;
  ...</pre>
      </td>
      <td><img src="https://user-images.githubusercontent.com/7046321/119829814-f156d300-befb-11eb-810a-249bc04248a2.jpg" alt="effect"></td>
    </tr>
    <tr>
      <td>select</td>
      <td>Select field. Dedicated for limited options, like pre-defined CSS classes or icons</td>
      <td>Same as for "input". The only difference is that <br> value of default has to cover one of defined options</td>
      <td>
        <strong>theme-myproject/src/etc/view.xml</strong><br>
<pre>...
  &lt;var name="fields"&gt;
    &lt;var name="1"&gt;
      &lt;var name="label"&gt;Teaser background&lt;/var&gt;
      &lt;var name="type"&gt;select&lt;/var&gt;
      &lt;var name="model"&gt;select_sample&lt;/var&gt;
      &lt;var name="note"&gt;Hey, this is example of "note"&gt;&lt;/var&gt;
      &lt;var name="options"&gt;select_sample&lt;/var&gt;
        &lt;var name="cs-image-teaser__slide--grey"&gt;&lt;/var&gt;
        &lt;var name="cs-image-teaser__slide--black"&gt;Black&lt;/var&gt;
        &lt;var name="cs-image-teaser__slide--white"&gt;White&lt;/var&gt;
      &lt;/var&gt;
      &lt;var name="default"&gt;cs-image-teaser__slide--white&lt;/var&gt;
      &lt;var name="frontend_type"&gt;css_class&lt;/var&gt;
    &lt;/var&gt;
  &lt;/var&gt;
  ...</pre>
      </td>
      <td><img src="https://user-images.githubusercontent.com/7046321/119832024-1a786300-befe-11eb-9ba1-e683d2d3ff7b.jpg" alt="effect"></td>
    </tr>
    <tr>
      <td>radio</td>
      <td>Standard options list</td>
      <td>Same as for "select"</td>
      <td>
        <strong>theme-myproject/src/etc/view.xml</strong><br>
<pre>...
  &lt;var name="fields"&gt;
    &lt;var name="1"&gt;
      &lt;var name="label"&gt;Radio list&lt;/var&gt;
      &lt;var name="type"&gt;radio&lt;/var&gt;
      &lt;var name="model"&gt;radio_sample&lt;/var&gt;
      &lt;var name="options"&gt;select_sample&lt;/var&gt;
        &lt;var name="option_1"&gt;Option #1&lt;/var&gt;
        &lt;var name="option_2"&gt;Option #2&lt;/var&gt;
        &lt;var name="option_3"&gt;Option #3&lt;/var&gt;
      &lt;/var&gt;
      &lt;var name="default"&gt;Option #2&lt;/var&gt;
    &lt;/var&gt;
  &lt;/var&gt;
  ...</pre>
      </td>
      <td><img src="https://user-images.githubusercontent.com/7046321/119832538-8eb30680-befe-11eb-9e75-2da2ee8eddc7.jpg" alt="effect"></td>
    </tr>
    <tr>
      <td>Position</td>
      <td>Position grid feature known from Content Align feature to set position of text for single teaser</td>
      <td>
        <ul>
          <li>label (string, required) - visible in CC</li>
          <li>model (string, required) - object key that you'll be <br>using on the frontend to retrieve- value of this field</li>
          <li>rows (number, required) - defines how many rows there <br>should be in the grid</li>
          <li>columns (number, required) - defines how many columns <br>there should be in the grid</li>
          <li>hint / note / warning (string, optional) - visible in CC <br>only, under defined field. Use it to describe the feature</li>
          <li>frontend_type (string, optional) - described later</li>
         <li>default (array, optional) - default value if needed</li>
        </ul>
<pre>// interface
  default = {
    x: 2, // for setting x-cord (row)
    y: 2 // for setting y-cord (column)
  }</pre>
      </td>
      <td><strong>theme-myproject/src/etc/view.xml</strong><br>
<pre>...
  &lt;var name="fields"&gt;
    &lt;var name="1"&gt;
      &lt;var name="label"&gt;Badge align&lt;/var&gt;
      &lt;var name="type"&gt;position&lt;/var&gt;
      &lt;var name="model"&gt;badge_align&lt;/var&gt;
      &lt;var name="rows"&gt;3&lt;/var&gt;
      &lt;var name="columnss"&gt;3&lt;/var&gt;
      &lt;var name="default"&gt;select_sample&lt;/var&gt;
        &lt;var name="x"&gt;1&lt;/var&gt;
        &lt;var name="y"&gt;1&lt;/var&gt;
      &lt;/var&gt;
      &lt;var name="warning"&gt;Note: Please verify text position
      configuration in the "Content" tab. It
      might overlap the badge position.&lt;/var&gt;
      &lt;var name="frontend_type"&gt;html&lt;/var&gt;
    &lt;/var&gt;
  &lt;/var&gt;
  ...</pre>
      </td>
      <td><img src="https://user-images.githubusercontent.com/7046321/119833366-59f37f00-beff-11eb-91c5-60cb388d8f06.jpg" alt="effect"></td>
    </tr>
    <tr>
      <td>Input</td>
      <td>Text type input. Dedicated for providing custom CSS classes or short content</td>
      <td>
        <ul>
          <li>label (string, required) - visible in CC</li>
          <li>model (string, required) - object key that you'll be <br>using on the frontend to retrieve- value of this field</li>
          <li>hint / note / warning (string, optional) - visible in CC <br>only, under defined field. Use it to describe the feature</li>
          <li>frontend_type (string, optional) - described later</li>
         <li>default (array, optional) - default value if needed</li>
        </ul>
      </td>
      <td><strong>theme-myproject/src/etc/view.xml</strong><br>
  <pre>...
    &lt;var name="fields"&gt;
      &lt;var name="1"&gt;
        &lt;var name="label"&gt;Text input&lt;/var&gt;
        &lt;var name="type"&gt;input&lt;/var&gt;
        &lt;var name="model"&gt;input_sample&lt;/var&gt;
        &lt;var name="hint"&gt;Hey, this is example of "hint"&lt;/var&gt;
        &lt;var name="default"&gt;Default input value&lt;/var&gt;
        &lt;var name="frontend_type"&gt;css_class&lt;/var&gt;
      &lt;/var&gt;
    &lt;/var&gt;
    ...</pre>
        </td>
      <td><img src="https://user-images.githubusercontent.com/7046321/119834186-046ba200-bf00-11eb-8961-52145306bb34.jpg" alt="effect"></td>
    </tr>
    <tr>
      <td>checkbox</td>
      <td>checkbox styled magento way (switcher-alike). Use it if you need boolean value on the frontend</td>
      <td>
        <ul>
          <li>label (string, required) - visible in CC</li>
          <li>model (string, required) - object key that you'll be <br>using on the frontend to retrieve- value of this field</li>
          <li>hint / note / warning (string, optional) - visible in CC <br>only, under defined field. Use it to describe the feature</li>
          <li>checked (boolean, optional) - default value <br>(if not set it will be set to false)</li>
          <li>frontend_type (string, optional) - described later</li>
        </ul>
      </td>
        <td>
          <strong>theme-myproject/src/etc/view.xml</strong><br>
  <pre>...
    &lt;var name="fields"&gt;
      &lt;var name="1"&gt;
        &lt;var name="label"&gt;Make logo bigger&lt;/var&gt;
        &lt;var name="type"&gt;checkbox&lt;/var&gt;
        &lt;var name="model"&gt;checkbox_sample&lt;/var&gt;
        &lt;var name="checked"&gt;true&lt;/var&gt;
        &lt;var name="frontend_type"&gt;html&lt;/var&gt;
      &lt;/var&gt;
    &lt;/var&gt;
    ...</pre>
        </td>
      <td><img src="https://user-images.githubusercontent.com/7046321/119834611-67f5cf80-bf00-11eb-9123-4b0614f081a2.jpg" alt="effect"></td>
    </tr>
  </tbody>
</table>

<h3>Rendering frontend</h3>

Image teaser and single slide got brand new file architecture to make it easier to manage data you get from custom fields. Previously Image Teaser template was divided into 2 separate templates, now each of them is divided into couple of more. The reason if it is maintainability. Since this component is very complex we want to avoid overrides that could take then hours to review after each update of core template. Now you can override only small part of it, or even better, if you fit into architecture, you can use hotspots. 

Hotspots are just empty templates that are rendered in predefined positions. Well, I wrote empty because they don't render anything, but actually they already have some variables predefined for you to use. You can thing about them just like about Magento's XML containers with this difference that they're defined in template and instead of referring to them, you need to do override. But hey, don't worry, they are empty in core anyway and there is no plan to update them in the future so go for it. 

<h3>Step by step</h3>

Not everything is clarified yet so lets create custom feature right now to have a full overview. We need 2 customizations, so we will follow 2 separate tasks.

Let's say core team and PO decided to not implement any of the things your client needs into the core. This is where we need to use the custom fields feature. For both our tasks our project is called Minisoft so our theme is theme-minisoft.

<h4>Task 1</h4>
<p><strong>Task:</strong> Client needs to display price of the product he put into image teaser and additionally he wants to select its position among 9 predefined, exactly the way text content is positioned.&nbsp;</p>

<ol>
  <li>
     I open my <em>theme-minisoft/src/etc/view.xml</em> and looking for&nbsp;<em>&lt;vars module="MageSuite_ContentConstructor"&gt;</em> vars set. If it doesn't exist yet I add it. Now having this I can configure my custom Tab in the teaser of CC and put some fields in it. We will use 2 fields here with following types:<br>
     <ol>
        <li><strong>textarea</strong> called Badge text - this will be content of our badge where client will use directive to get product's price,</li>
        <li><p><strong>position</strong> called Badge align with configuration of 3 rows and 3 columns - this will allow client to choose position he needs badge to be displayed in.</p>
`// theme-minisoft/src/etc/view.xml`<br>

```
<vars module="MageSuite_ContentConstructor">
    <var name="teaser">
        <var name="tabs">
            <var name="2">
                <var name="label">badge</var>
                <var name="content">
                    <var name="fields">
                        <var name="0">
                            <var name="label">Badge text</var>
                            <var name="type">textarea</var>
                            <var name="model">badge_text</var>
                            <var name="hint"><![CDATA[
                                Add content with special markup, e.g.:<br>
                                - <small>Only</small> {{price sku="some_sku"}}<br>
                                - {{sku sku="some_sku"}}<br>
                                - <big>Only</big> {{qty sku="some_sku"}} left
                            ]]></var>
                        </var>
                        <var name="1">
                            <var name="label">Badge align</var>
                            <var name="type">position</var>
                            <var name="model">badge_align</var>
                            <var name="rows">3</var>
                            <var name="columns">3</var>
                            <var name="default">
                                <var name="x">1</var>
                                <var name="y">1</var>
                            </var>
                            <var name="warning">Note: Please verify text position configuration in the "Content" tab. It might overlap the badge position.</var>
                        </var>
                    </var>
                </var>
            </var>
        </var>
    </var>
</vars>
```

<p>Within <strong>textarea</strong> field I included some <em>hint</em> for client so he knows what he can achieve with it.<br>For <strong>position </strong>I specified default for column: 1 and row: 1 to preselect position and make sure it will be chosen (it cannot be unselected). Here I also added <em>warning</em> to remind him that content align has the same configuration options and he should not overlap these 2<br><br></p>
        </li>
     </ol>
  </li>
  <li>I'm not running my node right now on the product so I need to rebuild my theme: <em>npx yarn build. </em>Then I'm checking Content Constructor to see if tab with both fields is rendered, and I see this:<br>
<img src="https://user-images.githubusercontent.com/7046321/119839358-662e0b00-bf04-11eb-9752-3423ea53c93c.jpg" alt="result"/>
<br><br></li>
  <li>
     <p>Now, I'm choosing some place in template where this would fit. Since content align works the same way I can put it on the same level, let's say after its node. From the list of hotspots I can see that could use hotspot <strong>before_content-wrapper</strong>. I'm overriding this template by duplicating it into <em>theme-minisoft/src/MageSuite_ContentConstructorFrontend/templates/component/image_teaser/slide_elements/hotspots/before_content-wrapper.phtml</em>&nbsp;and filling it with this content:</p>
`// theme-minisoft/src/Magento_ContentConstructorFrontend/templates/component/image_teaser/slide_elements/hotspots/before_content-wrapper.phtml`<br>

```
<?php
$slide = $block->getSlide();
 
$badgeText = $slide->getBadgeText();
$badgeAlign = $slide->getBadgeAlign();
$badgeClass = 'cs-image-teaser__badge';
 
if ($badgeAlign):
    if ($badgeAlign['x']):
        $badgeClass .= ' cs-image-teaser__badge--align-x-'.$badgeAlign['x'];
    endif;
    if ($badgeAlign['y']):
        $badgeClass .= ' cs-image-teaser__badge--align-x-'.$badgeAlign['y'];
    endif;
endif; ?>
 
<?php if ($badgeText): ?>
    <div class="<?= $badgeClass ?>">
        <span class="cs-image-teaser__badge-span"><?= $badgeText ?></span>
    </div>
<?php endif; ?>
```

<p>As you can see it's all based on 3 variables:</p>
     <ol>
        <li><strong>$slide</strong> - this one is already available in original template so I just leave it. It's a variable that stores configuration of whole teaser element</li>
        <li><strong>$badgeText</strong> - this is my custom field. It's mapped with the model I specified in my etc/view.xml and reached with standard Magento getter: (badge_text =&gt; getBadgeText())</li>
        <li><strong>$badgeAlign</strong> - this is an Array as specified in my etc/view.xml file. It stores 2 entries: 'x' to define column and 'y' to get a row.</li>
     </ol>
  </li>
  <li>
     After adding some styles I configure my image teaser and filling my badge with the following configuration to test if it works:
     <ol>
        <li><strong>badge_text</strong>:&nbsp;<em>Only {{price sku="pb90x"}}</em>,</li>
        <li><strong>badge_align</strong>: <em>x: 1, y: 3</em></li>
     </ol>
  </li>
</ol>
<br><br>
<h3>Task 2</h3>
<p><strong>Task:</strong> My designs says that my image teaser component can have either&nbsp;white (default), grey or black background. A client wants to decide on that while configuring component.</p>
<ol>
  <li>
     <p>First step is pretty much the same as for previous example. We will just define different structure. Note that this time we're not adding custom tab to the teaser but another section for global Image Teaser configuration because we need to apply background for entire component.</p>
`//theme-minisoft/src/etc/view.xml`<br>

```
<vars module="MageSuite_ContentConstructor">
    <var name="image_teaser">
        <var name="custom_sections">
            <var name="0">
                <var name="label">Advanced</var>
                <var name="content">
                    <var name="fields">
                        <var name="0">
                            <var name="label">Component's background color</var>
                            <var name="type">select</var>
                            <var name="model">background</var>
                            <var name="options">
                                <var name="cs-image-teaser--bg-white">White</var>
                                <var name="cs-image-teaser--bg-grey">Grey</var>
                                <var name="cs-image-teaser--bg-black">Black</var>
                            </var>
                            <var name="default">cs-image-teaser--bg-white</var>
                            <var name="frontend_type">css_class</var>
                        </var>
                    </var>
                </var>
            </var>
        </var>
    </var>
</vars>
```

<p>Since we want to have limited options I decided to use select-type field and define my options here.<br><br></p>


<h2>Important</h2>
<p>Please pay attention to the <strong>frontend_type</strong> entry that I introduced here, it's time to clarify that.<br>This entry is used to tell frontend part of component if this is <strong>html</strong> or <strong>css_class</strong>. Default value is <strong>html</strong> so I didn't specified that in previous task. If you specify this as css_class then chosen value will be automatically added to the class list of the component's container. No need to do anything else. Script magically finds all custom fields with this type, collecting them and adding to the property which is already included in the template.</p>
        <p>You can use this entry to add css classes to single teaser as well.</p>
  </li>
  <li>After covering given classes in CSS we're done.</li>
</ol>

**Comment by frqnck** [comment]
@mborkowski Awesome! Thank you so much for sharing this. Believe it or not, I had figured out a lot of this going thru cc_frontent & cc_admin source code but I was missing the logic for `frontend_type`. I have also updated the headline component to be able to add css_class.. may PR this later on.

**Comment by mborkowski** [comment]
Hello guys. Just FYI: we are currently extending some components and it's pretty possible that with next release most of them will have Custom Fields implemented. Still no option to create your own components though.

**Comment by roman204** [comment]
> Hello guys. Just FYI: we are currently extending some components and it's pretty possible that with next release most of them will have Custom Fields implemented. Still no option to create your own components though.

Awesome!😎

**Comment by drabikowy** [comment]
Hello all. Most of the components (except for cms block and custom html) support custom fields now. 
In next major release also block and custom html will support that. 
And whats more - we will finally have support for custom components, so you will be able to develop your own. It will come either within version 10 or 11 of MageSuite.
@roman204 @frqnck

**Comment by frqnck** [comment]
@drabikowy Thank you for the update. Sounds awesome. At present, we have custom forks for both content-constructor-* modules – looking forward to migrate back to the official modules once support for custom components is out...

**Comment by roman204** [comment]
> Hello all. Most of the components (except for cms block and custom html) support custom fields now. In next major release also block and custom html will support that. And whats more - we will finally have support for custom components, so you will be able to develop your own. It will come either within version 10 or 11 of MageSuite. @roman204 @frqnck

This is awesome news!!! Thanks for the update and the work.
